[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.19"
evm-version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
taiko = "${TAIKO_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
sepolia = "https://rpc.sepolia.org"	
mantle = "${MANTLE_RPC_URL}"


[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

